name: 'Typescript compiler'
description: 'Compile your Typescript code and check for errors.'
author: 'iCrawl'
branding:
  icon: alert-circle
  color: blue
inputs:
  project:
    description: 'Optional project path.'
    required: false
  build:
    description: 'Optional build reference path.'
    required: false
  executable:
    description: 'Compilation Executable (tsc or ttsc)'
    default: 'tsc'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
